dist: trusty
sudo: required
language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test     # newer toolchain
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2
  - export PATH=~/usr/bin:$PATH
  - echo $CXX
  - $CXX --version

install:
  - export CXX=g++-5
  - export CXX_FLAGS="${CXX_FLAGS} -Wall -Wextra -Werror -Weffc++ -Wlogical-op -Wshadow"
  - export CXX_FLAGS="${CXX_FLAGS} -fsanitize=${ASAN} -fno-omit-frame-pointer"
  - sudo apt-get update -qq
  - sudo apt-get remove cmake
  - sudo apt-get install -q -y libsdl2-dev libsdl2-image-dev g++-5

script:
  - version=3.9.6
  - wget https://cmake.org/files/v3.9/cmake-$version.tar.gz
  - tar -xzvf cmake-$version.tar.gz
  - cd cmake-$version/
  - ./bootstrap
  - make -j4
  - sudo make install
  - cd ..

  - mkdir buildMyProject
  - cd buildMyProject/
  - cmake ..
  - make
  - ./GameIsOn

notifications:
  email: false
