dist: trusty
sudo: required
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - llvm-toolchain-precise
      - ubuntu-toolchain-r/test     # newer toolchain
      - zoogie/sdl2-snapshots       # libsdl2
    packages:
      - cmake
      - cmake-data
      - g++-5
      - libsdl2-dev
      - libsdl2-image-dev

before_install:
  - echo $CXX
  - $CXX --version

install:
  - export CXX=g++-5
  - export CXX_FLAGS="${CXX_FLAGS} -Wall -Wextra -Werror -Weffc++ -Wlogical-op -Wshadow"
  - export CXX_FLAGS="${CXX_FLAGS} -fsanitize=${ASAN} -fno-omit-frame-pointer"

script:
  - mkdir build
  - cd build/
  - cmake ..
  - make
  - ./GameIsOn

notifications:
  email: false
